import streamlit as st

from llm import get_item_description

st.title('Sell you stuff with AI 🤖')
st.caption("Upload an image of an item you want to sell and get a description generated by AI.")


# Sidebar for uploading an image
images = st.file_uploader("Upload items", type=["jpg", "jpeg", "png"], accept_multiple_files=True)

if images:
    for image in images:
        with st.expander(image.name, expanded=True):
            st.image(image, caption='Uploaded Image', width=100)
            with st.chat_message('Item Description'):
                st.write(get_item_description(image))

st.sidebar.title("Sell your stuff 💰")
st.sidebar.markdown("Made by [Lukasz Kaniowski](https://twitter.com/lkaniowski) with 🧡")
st.sidebar.caption("If you have any suggestion or feedback just drop me a dm on [Twitter/X](https://twitter.com/lkaniowski)!")
st.sidebar.markdown("source code: [GitHub](https://github.com/lukasz-kaniowski/sell-your-stuff) 🐙")
